@startuml
hide footbox
skinparam sequenceParticipant underline
client -> server : connect()
client <-- server : accept()
client -> server : send(metadata)
client -> server : send(chunk_1)
client <-- server : ack()
client -> server : send(chunk_2)
client <-- server : ack()
... Repeat until finish ...
client -> server : send(chunk_n)
client <-- server : ack()
client -> server : disconnect()
@enduml
