@startuml
node Client as cli {
	component sender
	file "File" as f1
}
node Server as srv {
	component receiver
	file "File" as f2
}

sender <. f1 : Read
receiver .> f2 : Write

sender -- receiver : TCP/IP
@enduml
